# Generated by Django 3.2.6 on 2021-08-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210828_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(max_length=255, verbose_name='Content'),
        ),
    ]
