# Generated by Django 3.2.6 on 2021-09-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
